version: '3'
services:
  next:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      target: development
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: npm run dev
volumes:
  node_modules:
