import '@/style/globals.css';
import { type ReactNode } from 'react';
import { AppLayout } from '@/component/layout';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return <AppLayout>{children}</AppLayout>;
}
